
management.endpoints.web.exposure.include: "*"

server.port: "8080"


spring.datasource:
   url: jdbc:h2:file:./data/mydb
   #url: jdbc:h2:mem:mydb
   username: sa
   password: 
   driver-class-name: org.h2.Driver
   
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


course:
  message: "Prueba exitosa"
  service: "Mensaje desde servicio"
  